/****** Object:  Table [T_Internal_Standards] ******/
/****** RowCount: 25 ******/
SET IDENTITY_INSERT [T_Internal_Standards] ON
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (0,'unknown','status uncertain','All')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (1,'none','Nothing added','All')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (2,'PepChromeA','5 elution time marker peptides','Postdigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (3,'MiniProteomeA','3 proteins added prior to digestion (development work)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (4,'MiniProteomeB','3 proteins added prior to digestion; 6 peptides after digestion','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (5,'MP_05_01','Official mini proteome mix (October 2005)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (6,'MP_06_01','Official mini proteome mix (March 2006)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (7,'MP_06_02','Official mini proteome mix (December 2006)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (8,'QC_05_03','QC Standards mixture (2005)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (10,'MP_06_03','Official mini proteome mix (December 2006)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (11,'MP_07_01','Official mini proteome mix (December 2006)','Predigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (12,'MP_07_02','Official mini proteome mix (May 2007)','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (13,'MP_07_03','Official mini proteome mix (December 2007)','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (14,'MP_07_04','Official mini proteome mix (February 2008)','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (15,'MP_08_01','Official mini proteome mix (July 2008)','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (16,'ADHYeast','ADHYeast','PostDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (17,'ADHYeast_082308','ADHYeast_082308','PostDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (21,'MP_09_01','MP_09_01','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (22,'MP_09_02','MP_09_02','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (23,'mini-proteome','mini-proteome','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (24,'MP_09_03','MP_09_03','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (25,'MP_10_01','MP_10_01','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (26,'MP_10_02','MP_10_02','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (27,'MP_10_03','MP_10_03','PreDigest')
INSERT INTO [T_Internal_Standards] (Internal_Std_Mix_ID, Name, Description, Type) VALUES (28,'MP_10_04','MP_10_04','PreDigest')
SET IDENTITY_INSERT [T_Internal_Standards] OFF
