/****** Object:  Database [PT_Template_01] ******/
CREATE DATABASE [PT_Template_01] ON  PRIMARY 
( NAME = N'PT_Template_01_dat', FILENAME = N'F:\SQLServerData\PT_Template_01_data.mdf' , SIZE = 38912KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'PT_Template_01_log', FILENAME = N'F:\SQLServerData\PT_Template_01_log.ldf' , SIZE = 111616KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'PT_Template_01', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PT_Template_01].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [PT_Template_01] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PT_Template_01] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PT_Template_01] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PT_Template_01] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PT_Template_01] SET ARITHABORT OFF 
GO
ALTER DATABASE [PT_Template_01] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PT_Template_01] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [PT_Template_01] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PT_Template_01] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PT_Template_01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PT_Template_01] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PT_Template_01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PT_Template_01] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PT_Template_01] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PT_Template_01] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PT_Template_01] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PT_Template_01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PT_Template_01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PT_Template_01] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PT_Template_01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PT_Template_01] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PT_Template_01] SET  READ_WRITE 
GO
ALTER DATABASE [PT_Template_01] SET RECOVERY FULL 
GO
ALTER DATABASE [PT_Template_01] SET  MULTI_USER 
GO
ALTER DATABASE [PT_Template_01] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [PT_Template_01] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [D3J410]
GO
GRANT CONNECT TO [d3m578]
GO
GRANT CONNECT TO [msdadmin]
GO
GRANT CONNECT TO [MTAdmin]
GO
GRANT CONNECT TO [MTS_DB_DEV]
GO
GRANT SHOWPLAN TO [MTS_DB_DEV]
GO
GRANT CONNECT TO [MTS_DB_Lite]
GO
GRANT SHOWPLAN TO [MTS_DB_Lite]
GO
GRANT CONNECT TO [MTS_DB_Reader]
GO
GRANT SHOWPLAN TO [MTS_DB_Reader]
GO
GRANT CONNECT TO [MTUser]
GO
GRANT SHOWPLAN TO [MTUser]
GO
