/****** Object:  Table [T_Process_State] ******/
/****** RowCount: 29 ******/
/****** Columns: ID, Name ******/
INSERT INTO [T_Process_State] VALUES (0,'(na)')
INSERT INTO [T_Process_State] VALUES (3,'Load Failed')
INSERT INTO [T_Process_State] VALUES (4,'Load Skipped')
INSERT INTO [T_Process_State] VALUES (5,'Do Not Export')
INSERT INTO [T_Process_State] VALUES (6,'Holding')
INSERT INTO [T_Process_State] VALUES (7,'Joined into Segmented_Job')
INSERT INTO [T_Process_State] VALUES (10,'New')
INSERT INTO [T_Process_State] VALUES (20,'Peptides Loaded')
INSERT INTO [T_Process_State] VALUES (25,'SIC Stats Defined')
INSERT INTO [T_Process_State] VALUES (30,'Mass Tags Identified')
INSERT INTO [T_Process_State] VALUES (33,'Local sequences table updated')
INSERT INTO [T_Process_State] VALUES (35,'SIC Stat Update Required')
INSERT INTO [T_Process_State] VALUES (39,'Local sequences table updated, but holding since member of joined job')
INSERT INTO [T_Process_State] VALUES (40,'Ready for GANET Processing')
INSERT INTO [T_Process_State] VALUES (43,'GANET Save Error')
INSERT INTO [T_Process_State] VALUES (44,'GANET Processing Timeout Error')
INSERT INTO [T_Process_State] VALUES (45,'GANET Processing ready for regression')
INSERT INTO [T_Process_State] VALUES (46,'GANET Processing ready to load')
INSERT INTO [T_Process_State] VALUES (48,'GANET Load Error')
INSERT INTO [T_Process_State] VALUES (50,'GANET Calculated')
INSERT INTO [T_Process_State] VALUES (60,'Confidence Scores Calculated')
INSERT INTO [T_Process_State] VALUES (65,'New Filter Criteria Evaluation Required')
INSERT INTO [T_Process_State] VALUES (70,'Filter Criteria Evaluated')
INSERT INTO [T_Process_State] VALUES (75,'SIC Results Loaded')
INSERT INTO [T_Process_State] VALUES (90,'Ready for Peptide Prophet Processing')
INSERT INTO [T_Process_State] VALUES (94,'Peptide Prophet Processing Timeout Error')
INSERT INTO [T_Process_State] VALUES (95,'Peptide Prophet Processing ready for calculation')
INSERT INTO [T_Process_State] VALUES (96,'Peptide Prophet Processing ready to load')
INSERT INTO [T_Process_State] VALUES (98,'Peptide Prophet Processing Load Error')
