/****** Object:  Table [T_Process_Config] ******/
/****** RowCount: 21 ******/
SET IDENTITY_INSERT [T_Process_Config] ON
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (104,'DB_Schema_Version','2.0','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (110,'Enzyme_ID','10','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (108,'General_Statistics_Update_Interval','25','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (120,'Import_Result_Type','IN_Peptide_Hit','6/4/2009 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (122,'Import_Result_Type','MSG_Peptide_Hit','1/16/2012 12:00:00 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (100,'Import_Result_Type','Peptide_Hit','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (105,'Import_Result_Type','SIC','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (113,'Import_Result_Type','XT_Peptide_Hit','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (109,'Job_Info_DMS_Update_Interval','30','5/9/2007 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (102,'MTDB_Export_Filter_ID','117','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (121,'NET_Regression_Param_File_Name_by_Sample_Label','iTRAQ, LCMSWarp_30Sections_Min20pct_Min20Peptides_KeepUnknownModPeptides_SaveGlobalPlots_SaveFilteredJobPlots_2010-04-20.xml','10/12/2010 12:00:00 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (123,'NET_Regression_Param_File_Name_by_Sample_Label','iTRAQ8, LCMSWarp_30Sections_Min20pct_Min20Peptides_KeepUnknownModPeptides_SaveGlobalPlots_SaveFilteredJobPlots_2010-04-20.xml','7/20/2012 11:55:09 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (125,'NET_Regression_Param_File_Name_by_Sample_Label','TMT10, LCMSWarp_30Sections_Min20pct_Min20Peptides_KeepUnknownModPeptides_SaveGlobalPlots_SaveFilteredJobPlots_2010-04-20.xml','11/15/2016 11:54:29 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (124,'NET_Regression_Param_File_Name_by_Sample_Label','TMT6, LCMSWarp_30Sections_Min20pct_Min20Peptides_KeepUnknownModPeptides_SaveGlobalPlots_SaveFilteredJobPlots_2010-04-20.xml','6/20/2013 11:16:57 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (106,'NET_Update_Batch_Size','75','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (107,'NET_Update_Max_Peptide_Count','300000','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (101,'Organism_DB_File_Name','','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (103,'Peptide_Import_Filter_ID','196','7/23/2010 12:00:00 AM','PNL\D3L243')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (111,'Protein_Collection_Filter','','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (115,'Seq_Direction_Filter','decoy','11/27/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (112,'Seq_Direction_Filter','forward','9/1/2006 12:00:00 AM','PNL\mtsadmin')
SET IDENTITY_INSERT [T_Process_Config] OFF
