/****** Object:  Table [AlertSettings] ******/
/****** RowCount: 27 ******/
/****** Columns: AlertName, VariableName, Enabled, Value, Description ******/
INSERT INTO [AlertSettings] VALUES ('BlockingAlert','QueryValue',0x01,'10','Value is in seconds')
INSERT INTO [AlertSettings] VALUES ('BlockingAlert','QueryValue2',0x01,'20','Value is in seconds')
INSERT INTO [AlertSettings] VALUES ('CPUAlert','QueryValue',0x01,'85','Value is in percentage')
INSERT INTO [AlertSettings] VALUES ('CPUAlert','QueryValue2',0x01,'95','Value is in percentage')
INSERT INTO [AlertSettings] VALUES ('HealthReport','MaxDeadLockRows',0x01,'250','Maximum Deadlock rows to display')
INSERT INTO [AlertSettings] VALUES ('HealthReport','MaxErrorLogRows',0x01,'250','Maximum Error Log rows to display')
INSERT INTO [AlertSettings] VALUES ('HealthReport','MinLogFileSizeMB',0x01,'100','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowAllDisks',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowBackups',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowCPUStats',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowEmptySections',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowFullDBList',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowFullFileInfo',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowFullJobInfo',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowLogBackups',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowPerfStats',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('HealthReport','ShowSchemaChanges',0x00,'','Variable for the HealthReport')
INSERT INTO [AlertSettings] VALUES ('LogFiles','MinFileSizeMB',0x01,'100','Ignore LogFiles smaller than this threshold, in MB')
INSERT INTO [AlertSettings] VALUES ('LogFiles','QueryValue',0x01,'50','Value is in percentage')
INSERT INTO [AlertSettings] VALUES ('LogFiles','QueryValue2',0x01,'20','Value is in percentage')
INSERT INTO [AlertSettings] VALUES ('LongRunningJobs','QueryValue',0x01,'60','Value is in seconds')
INSERT INTO [AlertSettings] VALUES ('LongRunningQueries','Exclusion_Sql',0x01,'sqlBackup','SQL Like Clause')
INSERT INTO [AlertSettings] VALUES ('LongRunningQueries','QueryValue',0x01,'615','Value is in seconds')
INSERT INTO [AlertSettings] VALUES ('LongRunningQueries','QueryValue2',0x01,'1200','Value is in seconds')
INSERT INTO [AlertSettings] VALUES ('TempDB','MinFileSizeMB',0x01,'100','Ignore the tempDB if the log file size is below this threshold, in MB')
INSERT INTO [AlertSettings] VALUES ('TempDB','QueryValue',0x01,'50','Value is in percentage')
INSERT INTO [AlertSettings] VALUES ('TempDB','QueryValue2',0x01,'20','Value is in percentage')
