/****** Object:  Table [T_Peak_Matching_Requests] ******/
/****** RowCount: 5 ******/
SET IDENTITY_INSERT [T_Peak_Matching_Requests] ON
INSERT INTO [T_Peak_Matching_Requests] (Request, Name, Tool, Mass_Tag_Database, Analysis_Jobs, Parameter_file, MinimumHighNormalizedScore, MinimumHighDiscriminantScore, MinimumPeptideProphetProbability, MinimumPMTQualityScore, Limit_To_PMTs_From_Dataset, Comment, Requester, Created) VALUES (100,'Bogus_Request1','Viper','Bob','1,2,3','P123','0.5','0.2','0.3','0.4','0','Software Testing','','9/21/2009 12:00:00 AM')
INSERT INTO [T_Peak_Matching_Requests] (Request, Name, Tool, Mass_Tag_Database, Analysis_Jobs, Parameter_file, MinimumHighNormalizedScore, MinimumHighDiscriminantScore, MinimumPeptideProphetProbability, MinimumPMTQualityScore, Limit_To_PMTs_From_Dataset, Comment, Requester, Created) VALUES (101,'Bogus_Request2','Viper','Bob','1,2,3','P123','0.5','0','0.3','1','0','Software','','9/22/2009 1:09:04 PM')
INSERT INTO [T_Peak_Matching_Requests] (Request, Name, Tool, Mass_Tag_Database, Analysis_Jobs, Parameter_file, MinimumHighNormalizedScore, MinimumHighDiscriminantScore, MinimumPeptideProphetProbability, MinimumPMTQualityScore, Limit_To_PMTs_From_Dataset, Comment, Requester, Created) VALUES (102,'Bogus_999','Viper','George','100,200,300','Bozo','0.5','0.4','0.3','0','0','Junk','d3j410','9/22/2009 1:30:23 PM')
INSERT INTO [T_Peak_Matching_Requests] (Request, Name, Tool, Mass_Tag_Database, Analysis_Jobs, Parameter_file, MinimumHighNormalizedScore, MinimumHighDiscriminantScore, MinimumPeptideProphetProbability, MinimumPMTQualityScore, Limit_To_PMTs_From_Dataset, Comment, Requester, Created) VALUES (103,'Bogus_994','Viper','Edgar','100,200,300','Bozo','0.5','0.4','0.3','0','0','Junk','d3j410','9/22/2009 2:06:31 PM')
INSERT INTO [T_Peak_Matching_Requests] (Request, Name, Tool, Mass_Tag_Database, Analysis_Jobs, Parameter_file, MinimumHighNormalizedScore, MinimumHighDiscriminantScore, MinimumPeptideProphetProbability, MinimumPMTQualityScore, Limit_To_PMTs_From_Dataset, Comment, Requester, Created) VALUES (104,'Bogus_990','Viper','Charlie','100,200,300','VladViperSettings_Mouse_P504_11Da.ini','0.5','0.4','0.3','0','0','Junk','d3j410','9/23/2009 6:05:44 AM')
SET IDENTITY_INSERT [T_Peak_Matching_Requests] OFF
