-- From https://www.simple-talk.com/blogs/2013/12/02/tsql-code-to-explore-keys-in-a-database/

SELECT t.TABLE_CATALOG + '.' + t.TABLE_SCHEMA + '.' + t.TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES t
     LEFT OUTER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS c
       ON t.TABLE_CATALOG = c.TABLE_CATALOG AND
          t.TABLE_SCHEMA = c.TABLE_SCHEMA AND
          t.TABLE_NAME = c.TABLE_NAME AND
          CONSTRAINT_TYPE = 'PRIMARY KEY'
WHERE t.TABLE_TYPE = 'BASE TABLE' AND
      c.TABLE_NAME IS NULL
