/****** Object:  Table [T_Peak_Matching_Defaults] ******/
/****** RowCount: 9 ******/
SET IDENTITY_INSERT [T_Peak_Matching_Defaults] ON
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (100,'SW_Test_Bruker','','none','',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (101,'SW_TEST_FTICR','','none','',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (102,'11T_FTICR','','none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineTol_Export_SaveGraphics_2006-11-03.ini',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (103,'7T_FTICR','','none','',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (104,'9T_FTICR','','none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineTol_Export_SaveGraphics_2006-11-03.ini',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (105,'QTOF_MM1','','none','QT_UMCIonNet_NetAdjWarpTol30ppm_AMT30ppm_0.05NET_RefineTol_Export_SaveGraphicsAndGel_2006-11-03.ini',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (106,'11T_FTICR_B','','none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineTol_Export_SaveGraphics_2006-11-03.ini',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (107,'LTQ_FT1','','none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineTol_Export_SaveGraphics_2006-11-03.ini',0,'',1,0,0,1,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (108,'LTQ_Orb_1','','none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineTol_Export_SaveGraphics_2006-11-03.ini',0,'',1,0,0,1,5)
SET IDENTITY_INSERT [T_Peak_Matching_Defaults] OFF
