/****** Object:  Table [T_Process_Config] ******/
/****** RowCount: 33 ******/
SET IDENTITY_INSERT [T_Process_Config] ON
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (100,'Campaign','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (119,'Dataset_DMS_Creation_Date_Minimum','','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (129,'DB_Schema_Version','2.0','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (139,'GANET_Avg_Use_Max_Obs_Area_In_Job_Enabled','1','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (122,'GANET_Fit_Minimum_Average_GANET','0.8','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (115,'GANET_Fit_Minimum_Import','0','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (131,'GANET_RSquared_Minimum_Average_GANET','-1','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (132,'GANET_RSquared_Minimum_Import','0','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (121,'GANET_Weighted_Average_Enabled','1','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (135,'General_Statistics_Update_Interval','50','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (136,'Job_Info_DMS_Update_Interval','60','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (117,'MS_Instrument_Class','BRUKERFTMS','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (116,'MS_Instrument_Class','Finnigan_FTICR','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (133,'MS_Instrument_Class','LTQ_FT','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (112,'MS_Result_Type','HMMA_Peak','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (140,'MSMS_Result_Type','Peptide_Hit','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (144,'MSMS_Result_Type','XT_Peptide_Hit','2/10/2007 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (101,'Organism','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (110,'Organism_DB_File_Name','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (105,'Parameter_File_Name','sequest_N14_NE.params','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (103,'Peptide_DB_Name','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (114,'Peptide_Import_Filter_ID','117','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (137,'Peptide_Obs_Count_Filter_ID','141','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (123,'PMT_Quality_Score_Set_ID_and_Value','105, 1','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (130,'PMT_Quality_Score_Set_ID_and_Value','107, 2','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (138,'PMT_Quality_Score_Uses_Filtered_Peptide_Obs_Count','0','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (141,'Protein_Collection_Filter','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (102,'Protein_DB_Name','<Fill In>','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (104,'Separation_Type','LC-ISCO-Standard','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (143,'Seq_Direction_Filter','decoy','2/2/2007 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (142,'Seq_Direction_Filter','forward','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (109,'Settings_File_Name','AgilentDefSettings.xml','9/1/2006 12:00:00 AM','PNL\mtsadmin')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value, Last_Affected, Entered_By) VALUES (108,'Settings_File_Name','LCQDefSettings.txt','9/1/2006 12:00:00 AM','PNL\mtsadmin')
SET IDENTITY_INSERT [T_Process_Config] OFF
