/****** Object:  Table [T_Process_Config] ******/
/****** RowCount: 31 ******/
SET IDENTITY_INSERT [T_Process_Config] ON
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (100,'Campaign','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (101,'Organism','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (102,'Protein_DB_Name','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (103,'Peptide_DB_Name','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (104,'Separation_Type','LC-ISCO-Standard')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (105,'Parameter_File_Name','sequest_N14_NE.params')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (108,'Settings_File_Name','LCQDefSettings.txt')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (109,'Settings_File_Name','AgilentDefSettings.xml')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (110,'Organism_DB_File_Name','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (112,'MS_Result_Type','HMMA_Peak')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (114,'Peptide_Import_Filter_ID','117')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (115,'GANET_Fit_Minimum_Import','0')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (116,'MS_Instrument_Class','Finnigan_FTICR')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (117,'MS_Instrument_Class','BRUKERFTMS')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (119,'Dataset_DMS_Creation_Date_Minimum','')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (121,'GANET_Weighted_Average_Enabled','1')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (122,'GANET_Fit_Minimum_Average_GANET','0.8')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (123,'PMT_Quality_Score_Set_ID_and_Value','105, 1')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (129,'DB_Schema_Version','2.0')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (130,'PMT_Quality_Score_Set_ID_and_Value','107, 2')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (131,'GANET_RSquared_Minimum_Average_GANET','-1')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (132,'GANET_RSquared_Minimum_Import','0')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (133,'MS_Instrument_Class','LTQ_FT')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (135,'General_Statistics_Update_Interval','50')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (136,'Job_Info_DMS_Update_Interval','60')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (137,'Peptide_Obs_Count_Filter_ID','141')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (138,'PMT_Quality_Score_Uses_Filtered_Peptide_Obs_Count','0')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (139,'GANET_Avg_Use_Max_Obs_Area_In_Job_Enabled','1')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (140,'MSMS_Result_Type','Peptide_Hit')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (141,'Protein_Collection_Filter','<Fill In>')
INSERT INTO [T_Process_Config] (Process_Config_ID, Name, Value) VALUES (142,'Seq_Direction_Filter','forward')
SET IDENTITY_INSERT [T_Process_Config] OFF
