/****** Object:  Table [T_Quantitation_Defaults] ******/
/****** RowCount: 6 ******/
SET IDENTITY_INSERT [T_Quantitation_Defaults] ON
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (100,'DefaultSettings','',0.33,1,0,5000000000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (101,'9T_FTICR%','',0.33,1,0,5000000000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (102,'11T_FTICR%','',0.33,1,0,5000000000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (104,'LTQ_FT%','',0.33,1,0,100000000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (105,'QTOF_MM%','',0.33,1,0,10000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Maximum_Matches_per_UMC_to_Keep, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (106,'LTQ_Orb%','',0.33,1,0,100000000,0,0,0,0,0,0,6,1,0.25,0,0,1,0)
SET IDENTITY_INSERT [T_Quantitation_Defaults] OFF
