/****** Object:  Table [T_Quantitation_Defaults] ******/
/****** RowCount: 7 ******/
SET IDENTITY_INSERT [T_Quantitation_Defaults] ON
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (100,'DefaultSettings','',0.33,1,0,5000000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (101,'9T_FTICR','',0.33,1,0,5000000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (102,'11T_FTICR','',0.33,1,0,5000000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (103,'11T_FTICR_B','',0.33,1,0,5000000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (104,'LTQ_FT1','',0.33,1,0,100000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (105,'QTOF_MM1','',0.33,1,0,10000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
INSERT INTO [T_Quantitation_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Fraction_Highest_Abu_To_Use, Normalize_To_Standard_Abundances, Standard_Abundance_Min, Standard_Abundance_Max, UMC_Abundance_Mode, Expression_Ratio_Mode, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_PMT_Quality_Score, Minimum_Peptide_Length, Minimum_Match_Score, Minimum_Del_Match_Score, Minimum_Peptide_Replicate_Count, ORF_Coverage_Computation_Level, Internal_Std_Inclusion_Mode) VALUES (106,'LTQ_Orb_1','',0.33,1,0,100000000,0,0,0,0.2,0,6,0.35,0.1,0,1,0)
SET IDENTITY_INSERT [T_Quantitation_Defaults] OFF
