/****** Object:  Database [MT_HistoricLog] ******/
CREATE DATABASE [MT_HistoricLog] ON  PRIMARY 
( NAME = N'MT_HistoricLog_dat', FILENAME = N'F:\SQLServerData\MT_HistoricLog_data.mdf' , SIZE = 373504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'MT_HistoricLog_log', FILENAME = N'D:\SQLServerData\MT_HistoricLog_log.ldf' , SIZE = 1536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'MT_HistoricLog', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MT_HistoricLog].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [MT_HistoricLog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET ARITHABORT OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [MT_HistoricLog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MT_HistoricLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MT_HistoricLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MT_HistoricLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MT_HistoricLog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MT_HistoricLog] SET  READ_WRITE 
GO
ALTER DATABASE [MT_HistoricLog] SET RECOVERY FULL 
GO
ALTER DATABASE [MT_HistoricLog] SET  MULTI_USER 
GO
ALTER DATABASE [MT_HistoricLog] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [MT_HistoricLog] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [d3m578]
GO
GRANT CONNECT TO [DMSWebUser]
GO
GRANT CONNECT TO [h0693075]
GO
GRANT CONNECT TO [msdadmin]
GO
GRANT CONNECT TO [MTAdmin]
GO
GRANT CONNECT TO [MTS_DB_DEV]
GO
GRANT CONNECT TO [MTS_DB_Lite]
GO
GRANT CONNECT TO [MTUser]
GO
