/****** Object:  Table [T_Peak_Matching_Defaults] ******/
/****** RowCount: 8 ******/
SET IDENTITY_INSERT [T_Peak_Matching_Defaults] ON
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (106,'11T_FTICR_B',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineMassAndNETTol_Export_SaveGraphics_2006-11-08.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (107,'LTQ_FT1',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineMassAndNETTol_Export_SaveGraphics_2006-11-08.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (112,'Exact%',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_MaxData1500K_RefineMassAndNETTol_Export_SaveGraphics_2006-11-08.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (113,'%QExact%',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_MaxData1000K_RefineMassAndNETTol_Export_SaveGraphics_2015-07-13.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (114,'IMS%',null,'none','IMS_PredefinedFeatures_AllMappedPoints_NetAdjWarpTol25ppm_AMT25ppm_0.035NET_3msecDT_Export_SaveGraphics_2011-06-23.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (115,'VOrbiETD%',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_MaxData1000K_RefineMassAndNETTol_Export_SaveGraphics_2015-07-13.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (116,'%Orb%',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_RefineMassAndNETTol_Export_SaveGraphics_2006-11-08.ini',0,'',0,0,0,2,5)
INSERT INTO [T_Peak_Matching_Defaults] (Default_ID, Instrument_Name, Dataset_Name_Filter, Labelling_Filter, IniFile_Name, Confirmed_Only, Mod_List, Minimum_High_Normalized_Score, Minimum_High_Discriminant_Score, Minimum_Peptide_Prophet_Probability, Minimum_PMT_Quality_Score, Priority) VALUES (117,'Lumos%',null,'none','UMCIonNet_NetAdjWarpTol10ppm_AMT6ppm_0.025NET_MaxData1000K_RefineMassAndNETTol_Export_SaveGraphics_2015-07-13.ini',0,'',0,0,0,2,5)
SET IDENTITY_INSERT [T_Peak_Matching_Defaults] OFF
