/****** Object:  Database [MT_Main] ******/
CREATE DATABASE [MT_Main] ON  PRIMARY 
( NAME = N'MT_Main_Data', FILENAME = N'F:\SQLServerData\MT_Main_data.mdf' , SIZE = 629760KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'MT_Main_Log', FILENAME = N'D:\SQLServerData\MT_Main_log.ldf' , SIZE = 1130624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'MT_Main', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MT_Main].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [MT_Main] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MT_Main] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MT_Main] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MT_Main] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MT_Main] SET ARITHABORT OFF 
GO
ALTER DATABASE [MT_Main] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MT_Main] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [MT_Main] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MT_Main] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MT_Main] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MT_Main] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MT_Main] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MT_Main] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MT_Main] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MT_Main] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MT_Main] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MT_Main] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MT_Main] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MT_Main] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MT_Main] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MT_Main] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MT_Main] SET  READ_WRITE 
GO
ALTER DATABASE [MT_Main] SET RECOVERY FULL 
GO
ALTER DATABASE [MT_Main] SET  MULTI_USER 
GO
ALTER DATABASE [MT_Main] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [MT_Main] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [d3m578]
GO
GRANT CONNECT TO [dmswebuser]
GO
GRANT CONNECT TO [h0693075]
GO
GRANT CONNECT TO [msdadmin]
GO
GRANT CONNECT TO [MTAdmin]
GO
GRANT CONNECT TO [MTS_DB_DEV]
GO
GRANT CONNECT TO [MTS_DB_Lite]
GO
GRANT CONNECT TO [MTS_DB_Reader]
GO
GRANT CONNECT TO [MTUser]
GO
GRANT CONNECT TO [pnl\d3m651]
GO
