/****** Object:  Database [dbSNP] ******/
CREATE DATABASE [dbSNP] ON  PRIMARY 
( NAME = N'dbSNP', FILENAME = N'I:\SQLServerData\dbSNP.mdf' , SIZE = 24798208KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbSNP_log', FILENAME = N'H:\SQLServerData\dbSNP_log.ldf' , SIZE = 953280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [dbSNP] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbSNP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbSNP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbSNP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbSNP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbSNP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbSNP] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbSNP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbSNP] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [dbSNP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbSNP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbSNP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbSNP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbSNP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbSNP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbSNP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbSNP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbSNP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbSNP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbSNP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbSNP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbSNP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbSNP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbSNP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbSNP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbSNP] SET  READ_WRITE 
GO
ALTER DATABASE [dbSNP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dbSNP] SET  MULTI_USER 
GO
ALTER DATABASE [dbSNP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbSNP] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [MTAdmin] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Dev] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Dev] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Lite] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Lite] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Reader] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Reader] AS [dbo]
GO
GRANT CONNECT TO [MTUser] AS [dbo]
GO
GRANT SHOWPLAN TO [MTUser] AS [dbo]
GO
GRANT CONNECT TO [pnl\rodr657] AS [dbo]
GO
