/****** Object:  Database [Prism_IFC] ******/
CREATE DATABASE [Prism_IFC] ON  PRIMARY 
( NAME = N'PRISM_IFC_Data', FILENAME = N'I:\SQLServerData\Prism_IFC_data.mdf' , SIZE = 9088KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'PRISM_IFC_Log', FILENAME = N'I:\SQLServerData\Prism_IFC_log.ldf' , SIZE = 1280KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [Prism_IFC] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Prism_IFC].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Prism_IFC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Prism_IFC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Prism_IFC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Prism_IFC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Prism_IFC] SET ARITHABORT OFF 
GO
ALTER DATABASE [Prism_IFC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Prism_IFC] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Prism_IFC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Prism_IFC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Prism_IFC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Prism_IFC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Prism_IFC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Prism_IFC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Prism_IFC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Prism_IFC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Prism_IFC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Prism_IFC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Prism_IFC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Prism_IFC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Prism_IFC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Prism_IFC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Prism_IFC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Prism_IFC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Prism_IFC] SET  READ_WRITE 
GO
ALTER DATABASE [Prism_IFC] SET RECOVERY FULL 
GO
ALTER DATABASE [Prism_IFC] SET  MULTI_USER 
GO
ALTER DATABASE [Prism_IFC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Prism_IFC] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [D3E383] AS [dbo]
GO
GRANT CONNECT TO [D3J410] AS [dbo]
GO
GRANT CONNECT TO [D3L243] AS [dbo]
GO
GRANT CONNECT TO [d3m578] AS [dbo]
GO
GRANT CONNECT TO [dmswebuser] AS [dbo]
GO
GRANT CONNECT TO [msdadmin] AS [dbo]
GO
GRANT CONNECT TO [MTAdmin] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Dev] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Lite] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Reader] AS [dbo]
GO
GRANT CONNECT TO [MTUser] AS [dbo]
GO
