/****** Object:  Database [Master_Seq_Scratch] ******/
CREATE DATABASE [Master_Seq_Scratch] ON  PRIMARY 
( NAME = N'Master_Seq_Scratch_Data', FILENAME = N'I:\SQLServerData\Master_Seq_Scratch.mdf' , SIZE = 4416KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Master_Seq_Scratch_Log', FILENAME = N'H:\SQLServerData\Master_Seq_Scratch_log.ldf' , SIZE = 29504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [Master_Seq_Scratch] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Master_Seq_Scratch].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Master_Seq_Scratch] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET ARITHABORT OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Master_Seq_Scratch] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [Master_Seq_Scratch] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Master_Seq_Scratch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Master_Seq_Scratch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Master_Seq_Scratch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Master_Seq_Scratch] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Master_Seq_Scratch] SET  READ_WRITE 
GO
ALTER DATABASE [Master_Seq_Scratch] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Master_Seq_Scratch] SET  MULTI_USER 
GO
ALTER DATABASE [Master_Seq_Scratch] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [Master_Seq_Scratch] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [MTAdmin] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Dev] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Dev] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Lite] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Lite] AS [dbo]
GO
GRANT CONNECT TO [MTS_DB_Reader] AS [dbo]
GO
GRANT SHOWPLAN TO [MTS_DB_Reader] AS [dbo]
GO
GRANT CONNECT TO [MTUser] AS [dbo]
GO
